### PR TITLE
Create it.json

### PR DESCRIPTION
**Pull request by GregoryWarn**
Added Italian Localization based on en.json

### CODE REVIEW

**Comment by Roger92** [comment]
Can you combine your two changes into one PR :) It.json and the change in the module.json ;)

**Comment by Roger92** [comment]
Ant thx for the translation :)

**Comment by GregoryWarn** [comment]
> Ant thx for the translation :)

Thank you for your good module!
[it.json](https://github.com/user-attachments/files/16039632/it.json)
[module.json](https://github.com/user-attachments/files/16039633/module.json)

**Comment by Roger92** [comment]
I can download them and add them tomorrow :)   If you want to do it via a PR, then merge your two patch branches and create a PR with that one.

But i can do add your changes manually, thats fine too :)

**Comment by GregoryWarn** [comment]
> I can download them and add them tomorrow :) If you want to do it via a PR, then merge your two patch branches and create a PR with that one.
> 
> But i can do add your changes manually, thats fine too :)

I won't be at my PC till next Saturday, so manual change is a good and fast option :)
PS: my italian friends with a poor english (or german) reading will enjoy your module more than ever!

**Comment by Roger92** [comment]
Great to hear that it helps you and your friends :)

**Pull request closed without merging**
